package com.rozy.dailytracker.dekstop;

import com.rozy.dailytracker.main;
import com.rozy.dailytracker.management.writeHandler;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class userFrame extends javax.swing.JFrame {

    main main = new main();
    LocalDate currentDate = LocalDate.now();
    writeHandler writeHandler = new writeHandler();

    String[] yesNo = {"Tidak", "Ya"};
    String currentTime = "";

    int hour = 0, minute = 0, second = 0;
    boolean clickedActivity = false;
    boolean clickedIndex = false;
    boolean clickedDead = false;
    boolean darkMode = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(userFrame.class.getName());

    public userFrame() {
        initComponents();
        setSize(1280, 640);
        setResizable(false);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        homePanel1 = new javax.swing.JPanel();
        timeLabel = new javax.swing.JLabel();
        sessionLabel = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        goalPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        goalTable = new javax.swing.JTable() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // All cells are read-only
            }
        };
        addTBtn = new javax.swing.JButton();
        activityField = new javax.swing.JTextField();
        activityLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        indexField = new javax.swing.JTextField();
        rmBtn = new javax.swing.JButton();
        updBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        icon = new javax.swing.JCheckBox();
        userLabel = new javax.swing.JLabel();
        outBtn = new javax.swing.JButton();
        themeIcon = new javax.swing.JCheckBox();
        reloadBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backPanel.setBackground(new java.awt.Color(200, 200, 200));

        tabbedPanel.setBackground(new java.awt.Color(175, 175, 175));
        tabbedPanel.setForeground(new java.awt.Color(0, 0, 0));
        tabbedPanel.setAutoscrolls(true);
        tabbedPanel.setFont(new java.awt.Font("JetBrainsMonoNL NFP SemiBold", 0, 30)); // NOI18N
        tabbedPanel.setInheritsPopupMenu(true);

        homePanel.setBackground(new java.awt.Color(175, 175, 175));
        homePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        homePanel.setForeground(new java.awt.Color(0, 0, 0));

        homePanel1.setBackground(new java.awt.Color(190, 190, 190));
        homePanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(150, 150, 150), 2, true));

        timeLabel.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 0, 0));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeLabel.setText(currentTime);
        Timer timerDate = new Timer();
        TimerTask taskDate = new TimerTask() {
            @Override
            public void run() {
                LocalDateTime getcurrentTime = LocalDateTime.now();

                String hour = String.valueOf(getcurrentTime.getHour());
                String minute = String.valueOf(getcurrentTime.getMinute());
                String second = String.valueOf(getcurrentTime.getSecond());

                String showHour = hour;
                String showMinute = minute;
                String showSecond = second;

                if(Integer.parseInt(hour)>10) {showHour = hour;} else {showHour = "0" + hour;}
                if(Integer.parseInt(minute)>10) {showMinute = minute;} else {showMinute = "0" + minute;}
                if(Integer.parseInt(second)>10) {showSecond = second;} else {showSecond = "0" + second;}

                currentTime = ("Current Time: " + showHour + ":" + showMinute + ":" + showSecond);
                timeLabel.setText(currentTime);
            }
        };
        timerDate.schedule(taskDate, 0, 1000);

        sessionLabel.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 24)); // NOI18N
        sessionLabel.setForeground(new java.awt.Color(0, 0, 0));
        sessionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sessionLabel.setText(currentTime);
        Timer timerSession = new Timer();
        TimerTask taskSession = new TimerTask() {
            @Override
            public void run() {
                second++;
                if(second>=60){minute++;}if(minute>=60){hour++;}

                String showSecond = String.valueOf(second);
                String showMinute = String.valueOf(minute);
                String showHour = String.valueOf(hour);

                if(second>=10){showSecond = String.valueOf(second);} else {showSecond = "0" + String.valueOf(second);}
                if(minute>=10){showMinute = String.valueOf(minute);} else {showMinute = "0" + String.valueOf(minute);}
                if(hour>=10){showHour = String.valueOf(hour);} else {showHour = "0" + String.valueOf(hour);}

                currentTime = ("Session Time: " + showHour + ":" + showMinute + ":" + showSecond);
                sessionLabel.setText(currentTime);
            }
        };
        timerSession.schedule(taskSession, 0, 1000);

        countLabel.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 24)); // NOI18N
        countLabel.setForeground(new java.awt.Color(0, 0, 0));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countLabel.setText("");

        javax.swing.GroupLayout homePanel1Layout = new javax.swing.GroupLayout(homePanel1);
        homePanel1.setLayout(homePanel1Layout);
        homePanel1Layout.setHorizontalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(sessionLabel)
                    .addComponent(countLabel))
                .addContainerGap(819, Short.MAX_VALUE))
        );
        homePanel1Layout.setVerticalGroup(
            homePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sessionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(countLabel)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab("HOME", homePanel);

        goalPanel.setBackground(new java.awt.Color(175, 175, 175));
        goalPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        goalTable.setAutoCreateRowSorter(true);
        goalTable.setBackground(new java.awt.Color(155, 155, 155));
        goalTable.setForeground(new java.awt.Color(0, 0, 0));
        goalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Activity", "Created", "Deadline"
            }
        ));
        goalTable.setGridColor(new java.awt.Color(200, 200, 200));
        goalTable.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(goalTable);

        addTBtn.setBackground(new java.awt.Color(150, 150, 150));
        addTBtn.setFont(new java.awt.Font("JetBrainsMonoNL NFM Medium", 0, 18)); // NOI18N
        addTBtn.setForeground(new java.awt.Color(0, 0, 0));
        addTBtn.setText("ADD");
        addTBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addTBtn.addActionListener(this::addTBtnActionPerformed);

        activityField.setBackground(new java.awt.Color(200, 200, 200));
        activityField.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 13)); // NOI18N
        activityField.setForeground(new java.awt.Color(0, 0, 0));
        activityField.setText("Masukkan Nama Aktifitas...");
        activityField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        activityField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activityFieldMouseClicked(evt);
            }
        });

        activityLabel.setFont(new java.awt.Font("JetBrainsMonoNL NFP ExtraBold", 0, 14)); // NOI18N
        activityLabel.setForeground(new java.awt.Color(0, 0, 0));
        activityLabel.setText("Activity Name");

        dateLabel.setFont(new java.awt.Font("JetBrainsMonoNL NFP ExtraBold", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateLabel.setText("Deadline");

        dateField.setBackground(new java.awt.Color(200, 200, 200));
        dateField.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 13)); // NOI18N
        dateField.setForeground(new java.awt.Color(0, 0, 0));
        dateField.setText("Masukkan Deadline...");
        dateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateFieldMouseClicked(evt);
            }
        });

        indexField.setBackground(new java.awt.Color(200, 200, 200));
        indexField.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 12)); // NOI18N
        indexField.setForeground(new java.awt.Color(0, 0, 0));
        indexField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        indexField.setText("...");
        indexField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        indexField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                indexFieldMouseClicked(evt);
            }
        });

        rmBtn.setBackground(new java.awt.Color(150, 150, 150));
        rmBtn.setForeground(new java.awt.Color(0, 0, 0));
        rmBtn.setText("RM");
        rmBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rmBtn.addActionListener(this::rmBtnActionPerformed);

        updBtn.setBackground(new java.awt.Color(150, 150, 150));
        updBtn.setForeground(new java.awt.Color(0, 0, 0));
        updBtn.setText("UPD");
        updBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updBtn.addActionListener(this::updBtnActionPerformed);

        searchField.setBackground(new java.awt.Color(150, 150, 150));
        searchField.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 16)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 0, 0));
        searchField.setText("Search...");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(150, 150, 150));
        saveBtn.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn.setText("SAVE");
        saveBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        javax.swing.GroupLayout goalPanelLayout = new javax.swing.GroupLayout(goalPanel);
        goalPanel.setLayout(goalPanelLayout);
        goalPanelLayout.setHorizontalGroup(
            goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goalPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goalPanelLayout.createSequentialGroup()
                            .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateLabel)
                                .addGroup(goalPanelLayout.createSequentialGroup()
                                    .addComponent(indexField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(109, 109, 109))
                        .addGroup(goalPanelLayout.createSequentialGroup()
                            .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(goalPanelLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(updBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(goalPanelLayout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, goalPanelLayout.createSequentialGroup()
                        .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(activityField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(activityLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        goalPanelLayout.setVerticalGroup(
            goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goalPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(activityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(goalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(goalPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("GOAL", goalPanel);

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(tabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userPanel.setBackground(new java.awt.Color(150, 150, 150));

        icon.setContentAreaFilled(false);
        if (main.userLogged.equals("admin")) {
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rozy/dailytracker/images/adminIcon.png")));
        } else {
            icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rozy/dailytracker/images/userIcon.png")));
        }

        userLabel.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 24)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText(main.userLogged);

        outBtn.setBackground(new java.awt.Color(255, 255, 255));
        outBtn.setFont(new java.awt.Font("JetBrainsMonoNL NFP Medium", 0, 24)); // NOI18N
        outBtn.setForeground(new java.awt.Color(0, 0, 0));
        outBtn.setText("LOG OUT");
        outBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        outBtn.addActionListener(this::outBtnActionPerformed);

        themeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rozy/dailytracker/images/sun.png"))); // NOI18N
        themeIcon.addActionListener(this::themeIconActionPerformed);

        reloadBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rozy/dailytracker/images/reload.png"))); // NOI18N
        reloadBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadBoxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userPanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(themeIcon)
                .addGap(36, 36, 36)
                .addComponent(reloadBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(themeIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reloadBox, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(outBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) goalTable.getModel();

        String filePath = writeHandler.filePath;
        File file = new File(filePath);

        try {
            FileReader reader = new FileReader(file);
            BufferedReader buffered = new BufferedReader(reader);

            Object[] lines = buffered.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split("///");
                model.addRow(row);
            }

            countLabel.setText("Jumlah Target : " + String.valueOf(goalTable.getRowCount()));
        } catch (Exception e) {
        }
    }

    private void outBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outBtnActionPerformed
        int yn = (JOptionPane.showOptionDialog(null, "Apakah Anda Yakin?", "Daily Tracker", 0,
                JOptionPane.QUESTION_MESSAGE, null, yesNo, 0));

        if (yn == 1) {
            JOptionPane.showMessageDialog(null, "Anda telah Keluar dari Akun Anda",
                    "Daily Tracker", JOptionPane.WARNING_MESSAGE);
            loginFrame loginFrame = new loginFrame();
            loginFrame.mainFrame();

            String filePath = writeHandler.filePath;
            File file = new File(filePath);
            try {
                FileWriter fw = new FileWriter(file);
                BufferedWriter buffered = new BufferedWriter(fw);

                for (int i = 0; i < goalTable.getRowCount(); i++) {
                    for (int j = 0; j < goalTable.getColumnCount(); j++) {
                        buffered.write(goalTable.getValueAt(i, j).toString() + "///");
                    }
                    buffered.newLine();
                }

                buffered.close();
                fw.close();
            } catch (IOException e) {
            }
            dispose();
        }
    }//GEN-LAST:event_outBtnActionPerformed

    private void addTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) goalTable.getModel();
        if (activityField.getText().equals("Masukkan Nama Aktifitas...") || dateField.getText().equals("Masukkan Deadline...")
                || activityField.getText().equals("") || dateField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap Masukkan Target",
                    "Daily Tracker", JOptionPane.ERROR_MESSAGE);
        } else {
            String number = String.valueOf(goalTable.getRowCount());
            String activity = activityField.getText();
            String created = String.valueOf(currentDate);
            String deadline = dateField.getText();

            Object[] obj = new Object[]{
                (number), (activity),
                (created), (deadline)
            };

            model.addRow((Object[]) obj);

            activityField.setText("Masukkan Nama Aktifitas...");
            dateField.setText("Masukkan Deadline...");
            clickedActivity = false;
            clickedDead = false;
            JOptionPane.showMessageDialog(null, "Target Telah Ditambahkan",
                    "Daily Tracker", JOptionPane.INFORMATION_MESSAGE);
            countLabel.setText("Jumlah Target : " + String.valueOf(goalTable.getRowCount()));
        }

    }//GEN-LAST:event_addTBtnActionPerformed

    private void activityFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activityFieldMouseClicked
        if (!clickedActivity) {
            activityField.setText("");
        } else {
        }
        clickedActivity = true;
    }//GEN-LAST:event_activityFieldMouseClicked

    private void dateFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateFieldMouseClicked
        if (!clickedDead) {
            dateField.setText("");
        } else {
        }
        clickedDead = true;
    }//GEN-LAST:event_dateFieldMouseClicked

    private void themeIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeIconActionPerformed
        if (darkMode) {

            darkMode = false;

            themeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rozy/dailytracker/images/moon.png")));

            goalTable.setBackground(new java.awt.Color(150, 150, 150));
            goalTable.setGridColor(new java.awt.Color(100, 100, 100));

            goalPanel.setBackground(new java.awt.Color(75, 75, 75));

            userPanel.setBackground(new java.awt.Color(50, 50, 50));

            tabbedPanel.setBackground(new java.awt.Color(75, 75, 175));
            tabbedPanel.setForeground(new java.awt.Color(200, 200, 200));

            homePanel.setBackground(new java.awt.Color(75, 75, 75));
            homePanel1.setBackground(new java.awt.Color(90, 90, 90));
            backPanel.setBackground(new java.awt.Color(100, 100, 100));

            activityField.setBackground(new java.awt.Color(100, 100, 100));
            activityField.setForeground(new java.awt.Color(225, 225, 225));

            dateField.setBackground(new java.awt.Color(100, 100, 100));
            dateField.setForeground(new java.awt.Color(225, 225, 225));

            indexField.setBackground(new java.awt.Color(100, 100, 100));
            indexField.setForeground(new java.awt.Color(200, 200, 200));

            userLabel.setForeground(new java.awt.Color(255, 255, 255));
            activityLabel.setForeground(new java.awt.Color(255, 255, 255));
            dateLabel.setForeground(new java.awt.Color(255, 255, 255));
            timeLabel.setForeground(new java.awt.Color(255, 255, 255));
            sessionLabel.setForeground(new java.awt.Color(255, 255, 255));
            countLabel.setForeground(new java.awt.Color(255, 255, 255));

            outBtn.setBackground(new java.awt.Color(0, 0, 0));
            outBtn.setForeground(new java.awt.Color(250, 250, 250));

            addTBtn.setBackground(new java.awt.Color(50, 50, 50));
            addTBtn.setForeground(new java.awt.Color(250, 250, 250));

            saveBtn.setBackground(new java.awt.Color(50, 50, 50));
            saveBtn.setForeground(new java.awt.Color(250, 250, 250));

            updBtn.setBackground(new java.awt.Color(50, 50, 50));
            updBtn.setForeground(new java.awt.Color(250, 250, 250));

            rmBtn.setBackground(new java.awt.Color(50, 50, 50));
            rmBtn.setForeground(new java.awt.Color(250, 250, 250));

            searchField.setBackground(new java.awt.Color(50, 50, 50));
            searchField.setForeground(new java.awt.Color(200, 200, 200));
        } else {

            darkMode = true;

            themeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rozy/dailytracker/images/sun.png")));

            goalTable.setBackground(new java.awt.Color(155, 155, 155));
            goalTable.setGridColor(new java.awt.Color(200, 200, 200));

            goalPanel.setBackground(new java.awt.Color(175, 175, 175));

            userPanel.setBackground(new java.awt.Color(150, 150, 150));

            tabbedPanel.setBackground(new java.awt.Color(175, 175, 175));
            tabbedPanel.setForeground(new java.awt.Color(0, 0, 0));

            homePanel.setBackground(new java.awt.Color(175, 175, 175));
            backPanel.setBackground(new java.awt.Color(200, 200, 200));
            homePanel1.setBackground(new java.awt.Color(190, 190, 190));

            activityField.setBackground(new java.awt.Color(200, 200, 200));
            activityField.setForeground(new java.awt.Color(0, 0, 0));

            dateField.setBackground(new java.awt.Color(200, 200, 200));
            dateField.setForeground(new java.awt.Color(0, 0, 0));

            indexField.setBackground(new java.awt.Color(200, 200, 200));
            indexField.setForeground(new java.awt.Color(0, 0, 0));

            userLabel.setForeground(new java.awt.Color(0, 0, 0));
            activityLabel.setForeground(new java.awt.Color(0, 0, 0));
            dateLabel.setForeground(new java.awt.Color(0, 0, 0));
            sessionLabel.setForeground(new java.awt.Color(0, 0, 0));
            timeLabel.setForeground(new java.awt.Color(0, 0, 0));
            countLabel.setForeground(new java.awt.Color(0, 0, 0));

            outBtn.setBackground(new java.awt.Color(255, 255, 255));
            outBtn.setForeground(new java.awt.Color(0, 0, 0));

            addTBtn.setBackground(new java.awt.Color(150, 150, 150));
            addTBtn.setForeground(new java.awt.Color(0, 0, 0));

            saveBtn.setBackground(new java.awt.Color(150, 150, 150));
            saveBtn.setForeground(new java.awt.Color(0, 0, 0));

            updBtn.setBackground(new java.awt.Color(150, 150, 150));
            updBtn.setForeground(new java.awt.Color(0, 0, 0));

            rmBtn.setBackground(new java.awt.Color(150, 150, 150));
            rmBtn.setForeground(new java.awt.Color(0, 0, 0));

            searchField.setBackground(new java.awt.Color(150, 150, 150));
            searchField.setForeground(new java.awt.Color(0, 0, 0));
        }


    }//GEN-LAST:event_themeIconActionPerformed

    private void indexFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_indexFieldMouseClicked
        if (!clickedIndex) {
            indexField.setText("");
        } else {
        }
        clickedIndex = true;
    }//GEN-LAST:event_indexFieldMouseClicked

    private void rmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) goalTable.getModel();
        try {
            int row = Integer.parseInt(indexField.getText());
            if (goalTable.isEditing()) {
                goalTable.getCellEditor().stopCellEditing();
            }

            model.removeRow(row);
            for (int i = 0; i < goalTable.getRowCount(); i++) {
                model.setValueAt(i, i, 0);
            }

            JOptionPane.showMessageDialog(null, "Target Telah Terhapus",
                    "Daily Tracker", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Index Tidak Tersedia",
                    "Daily Tracker", JOptionPane.ERROR_MESSAGE);
        }

        countLabel.setText("Jumlah Target : " + String.valueOf(goalTable.getRowCount()));

    }//GEN-LAST:event_rmBtnActionPerformed

    private void updBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) goalTable.getModel();
        try {
            int row = Integer.parseInt(indexField.getText());
            if (activityField.getText().equals("Masukkan Nama Aktifitas...") || dateField.getText().equals("Masukkan Deadline...")
                    || activityField.getText().equals("") || dateField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Harap Masukkan Target",
                        "Daily Tracker", JOptionPane.ERROR_MESSAGE);
            } else {
                model.setValueAt(activityField.getText(), row, 1);
                model.setValueAt(dateField.getText(), row, 3);
                JOptionPane.showMessageDialog(null, "Target Telah Diperbarui",
                        "Daily Tracker", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Index Tidak Tersedia",
                    "Daily Tracker", HEIGHT);
        }
        activityField.setText("Masukkan Nama Aktifitas...");
        dateField.setText("Masukkan Deadline...");
        clickedActivity = false;
        clickedDead = false;
    }//GEN-LAST:event_updBtnActionPerformed

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        String checker = searchField.getText();
        if (checker.equals("Search...")) {
            searchField.setText("");
        }
    }//GEN-LAST:event_searchFieldMouseClicked

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        DefaultTableModel table = (DefaultTableModel) goalTable.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(table);
        goalTable.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(searchField.getText()));
    }//GEN-LAST:event_searchFieldKeyReleased

    private void reloadBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadBoxMouseClicked
        DefaultTableModel model = (DefaultTableModel) goalTable.getModel();
        String filePath = writeHandler.filePath;
        File file = new File(filePath);

        model.setRowCount(0);
        try {
            FileReader reader = new FileReader(file);
            BufferedReader buffered = new BufferedReader(reader);

            Object[] lines = buffered.lines().toArray();

            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split("///");
                model.addRow(row);
            }

            for (int i = 0; i < goalTable.getRowCount(); i++) {
                model.setValueAt(i, i, 0);
            }

            FileWriter fw = new FileWriter(file);
            BufferedWriter bufferedw = new BufferedWriter(fw);

            for (int i = 0; i < goalTable.getRowCount(); i++) {
                for (int j = 0; j < goalTable.getColumnCount(); j++) {
                    bufferedw.write(goalTable.getValueAt(i, j).toString() + "///");
                }
                bufferedw.newLine();
            }

            buffered.close();
            fw.close();
        } catch (Exception e) {
        }

        countLabel.setText("Jumlah Target : " + String.valueOf(goalTable.getRowCount()));

    }//GEN-LAST:event_reloadBoxMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String filePath = writeHandler.filePath;
        File file = new File(filePath);
        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter buffered = new BufferedWriter(fw);

            for (int i = 0; i < goalTable.getRowCount(); i++) {
                for (int j = 0; j < goalTable.getColumnCount(); j++) {
                    buffered.write(goalTable.getValueAt(i, j).toString() + "///");
                }
                buffered.newLine();
            }

            buffered.close();
            fw.close();
        } catch (Exception e) {
            System.err.println("ERROR");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void mainFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new userFrame().setVisible(true));
        JOptionPane.showMessageDialog(null, "Selamat Datang! " + main.userLogged,
                "Daily Tracker", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activityField;
    private javax.swing.JLabel activityLabel;
    private javax.swing.JButton addTBtn;
    private javax.swing.JPanel backPanel;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel goalPanel;
    private javax.swing.JTable goalTable;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel homePanel1;
    private javax.swing.JCheckBox icon;
    private javax.swing.JTextField indexField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton outBtn;
    private javax.swing.JCheckBox reloadBox;
    private javax.swing.JButton rmBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel sessionLabel;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JCheckBox themeIcon;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JButton updBtn;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
